### PR TITLE
Fix tag inside string being treated as closing tag

### PR DESCRIPTION
**Pull request by VandeurenGlenn**
Fixes Uncaught SyntaxError: Unexpected token ILLEGAL

### CODE REVIEW

**Comment by VandeurenGlenn** [comment]
Or maybe its better using the dom for this? [comment](https://github.com/VandeurenGlenn/Atom-PolymerSnippets/commit/d2ba7122e3378c6885c343ea2e54c0e5505a18cb)

**Comment by jordanbtucker** [comment]
Or maybe it's better to just include the polyfill and let it determine whether it's needed. What is the real world performance gain of checking whether the polyfill is needed rather than just loading it?

**Comment by VandeurenGlenn** [comment]
@jordanbtucker I'm not an expert on the field butt I think their is some minor gain,
did some testing.
- just importing 474 - 497 ms.
- using the dom 140 - 177 ms
- using document.write 140 - 155 ms 

I don't know if these are trust worthy or not just used developer tools to check the load time.

**Comment by robdodson** [comment]
@VandeurenGlenn which browser was throwing the error?

**Comment by mateusortiz** [comment]
I just test in chrome canary is working

**Comment by jordanbtucker** [comment]
I'm not an expert in the performance field either, but maybe I'm asking the right question for the wrong reason.
1. Suppose that webcomponents.js adds a polyfill for a new feature called `x`.
2. A developer starts using `x` as if it were native because polymer-snippets includes webcomponents.js.
3. polymer-snippets only checks native support for `a`, `b`, and `c`, but not `x`, so `x` only works if it's natively supported.

Possible solutions for polymer-snippets include:
1. Always including webcomponents.js.
2. Keeping polymer-snippets up to date with native support checks for all webcomponents.js polyfills.
3. Locking webcomponents.js to versions that do not add polyfills.
4. Repeating solutions 2 and 3.

**Comment by VandeurenGlenn** [comment]
@robdodson Chrome, Firefox & IE, I'm running Windows so probably that's the reason.

@jordanbtucker Even didn't thought of that, if I understand correctly than would prefer solution 2.

**Comment by jordanbtucker** [comment]
This PR doesn't fix the error, but actually produces the same HTML that's causing the error.

I couldn't figure out how, if possible, to add a commit to this pull request, so I created a new one (#4) with a fix that works.

Thanks @VandeurenGlenn for finding this bug and reporting it.

**Comment by VandeurenGlenn** [comment]
@jordanbtucker  Darn, thought it did, sorry for that & glad I could help!

Edit: did you clone my repo for adding a new commit? I think adding a commit to a PR only works when you push to the used githubUser/branch for that PR.

**Pull request closed without merging**
